#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8ng9i3tqb8s73d5i1cg-a.virginia-postgres.render.com/expensemanager1
spring.datasource.username=expensemanager1_user
spring.datasource.password=LKTuprefBHVQX0OrxhcUEppyaZm2CNFt